# Generated by Django 3.2.5 on 2021-08-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210811_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='Others', max_length=64),
        ),
    ]
