# Generated by Django 3.2.5 on 2021-08-13 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
