# Generated by Django 3.2.5 on 2021-08-16 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='unliked',
            field=models.ManyToManyField(related_name='unliked_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Unlike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlikedpost', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlikeduser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
