# Generated by Django 3.2.5 on 2021-08-16 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20210816_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unlike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlikedpost', to='website.post'),
        ),
    ]
