# Generated by Django 3.2.5 on 2021-09-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20210823_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Tech', 'Tech'), ('Gardening', 'Gardening'), ('Finance', 'Finance'), ('Remote Work', 'Remote Work'), ('Design', 'Design')], default='Others', max_length=64),
        ),
    ]
