# Generated by Django 3.2.5 on 2021-10-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Arts & Entertainment', 'Arts & Entertainment'), ('Autos & Vehicles', 'Autos & Vehicles'), ('Beauty & Fitness', 'Beauty & Fitness'), ('Books & Literature', 'Books & Literature'), ('Business & Industrial', 'Business & Industrial'), ('Computers & Electronics', 'Computers & Electronics'), ('Finance', 'Finance'), ('Food & Drink', 'Food & Drink'), ('Gambling & Betting', 'Gambling & Betting'), ('Games', 'Games'), ('Health', 'Health'), ('Hobbies & Leisure', 'Hobbies & Leisure'), ('Home & Garden', 'Home & Garden'), ('Internet & Telecom', 'Internet & Telecom'), ('Jobs & Education', 'Jobs & Education'), ('Law & Government', 'Law & Government'), ('News', 'News'), ('Online Communities', 'Online Communities'), ('People & Society', 'People & Society'), ('Pets & Animals', 'Pets & Animals'), ('Real Estate', 'Real Estate'), ('Reference', 'Reference'), ('Science', 'Science'), ('Shopping', 'Shopping'), ('Sports', 'Sports'), ('Travel', 'Travel'), ('Others', 'Others')], default='Others', max_length=64),
        ),
    ]
