# Generated by Django 3.2.5 on 2021-10-31 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_post_updated_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='editedtrue',
            field=models.CharField(default='', max_length=64),
        ),
    ]
