# Generated by Django 3.2.5 on 2021-10-31 07:20

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_post_editedtrue'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpost',
            name='editedtrue',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='subpost',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='subpost',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='subpost',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='subpost',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='subpost',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='subpost',
            name='title',
            field=models.CharField(default='Untitled', max_length=64),
        ),
        migrations.RemoveField(
            model_name='post',
            name='subposts',
        ),
        migrations.AddField(
            model_name='post',
            name='subposts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subposts', to='website.subpost'),
        ),
        migrations.AlterField(
            model_name='subpost',
            name='post',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subpost',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
