# Generated by Django 3.2.5 on 2021-10-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_auto_20211031_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subposts',
        ),
        migrations.AddField(
            model_name='post',
            name='subposts',
            field=models.ManyToManyField(null=True, related_name='subposts', to='website.Subpost'),
        ),
    ]
