# Generated by Django 3.2.5 on 2021-10-31 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_auto_20211031_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subposts',
        ),
        migrations.AddField(
            model_name='subpost',
            name='parentpost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentpost', to='website.post'),
        ),
    ]
