# Generated by Django 3.2.5 on 2021-10-31 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_auto_20211031_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subpost',
            name='parentpost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='website.post'),
        ),
    ]
