# Generated by Django 3.2.5 on 2021-11-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='favouritetrue',
            field=models.CharField(default='', max_length=64),
        ),
    ]
