# Generated by Django 3.2.5 on 2021-11-01 07:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_favourite_favouritetrue'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favourited',
            field=models.ManyToManyField(related_name='favourited_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
