# Generated by Django 3.2.5 on 2021-11-01 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_post_favourited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='favouritetrue',
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='post',
        ),
        migrations.AddField(
            model_name='favourite',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favouritedpost', to='website.post'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favouriteduser', to=settings.AUTH_USER_MODEL),
        ),
    ]
