# Generated by Django 3.2.5 on 2021-11-03 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_auto_20211101_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postowner', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postchat', to='website.post')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postvisitor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
