# Generated by Django 3.2.5 on 2021-11-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_chat_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='notification',
            field=models.IntegerField(null=True),
        ),
    ]
