# Generated by Django 3.2.5 on 2021-11-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_chat_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='notification',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
