# Generated by Django 3.2.5 on 2021-11-08 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0045_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatedchat', to='website.chat'),
        ),
    ]
