# Generated by Django 3.2.5 on 2021-11-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_notification_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='notification',
            field=models.CharField(default='', max_length=64),
        ),
    ]
