# Generated by Django 3.2.5 on 2021-11-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0048_chat_lastsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updates',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
